
import { Template, Asset } from './types';

export const TEMPLATES: Template[] = [
  {
    id: '1',
    name: '樱花之梦',
    tag: '#粉色',
    imageUrl: 'https://picsum.photos/seed/cherry/400/533',
    isDynamic: true
  },
  {
    id: '2',
    name: '霓虹都市',
    tag: '#赛博朋克',
    imageUrl: 'https://picsum.photos/seed/neon/400/533',
    isDynamic: true
  },
  {
    id: '3',
    name: '夏日微风',
    tag: '#清新',
    imageUrl: 'https://picsum.photos/seed/summer/400/533',
    isDynamic: true
  },
  {
    id: '4',
    name: '惬意雨天',
    tag: '#治愈',
    imageUrl: 'https://picsum.photos/seed/rain/400/533',
    isDynamic: true
  },
  {
    id: '5',
    name: '校园时光',
    tag: '#日常',
    imageUrl: 'https://picsum.photos/seed/school/400/533',
    isDynamic: false
  },
  {
    id: '6',
    name: '星之魔法',
    tag: '#梦幻',
    imageUrl: 'https://picsum.photos/seed/magic/400/533',
    isDynamic: true
  }
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'a1',
    name: '未来少女_V2',
    timestamp: 'Just now',
    imageUrl: 'https://picsum.photos/seed/cyber/400/533',
    status: 'completed',
    isDynamic: true,
    isFavorited: false
  },
  {
    id: 'a2',
    name: 'IMG_2931.jpg',
    timestamp: '2h ago',
    imageUrl: 'https://picsum.photos/seed/photo/400/533',
    status: 'original',
    isFavorited: true
  },
  {
    id: 'a3',
    name: '梦境_Final',
    timestamp: 'Processing...',
    imageUrl: 'https://picsum.photos/seed/dream/400/533',
    status: 'processing',
    isFavorited: false
  },
  {
    id: 'a4',
    name: '赛博朋克_01',
    timestamp: 'Failed',
    imageUrl: 'https://picsum.photos/seed/cyber2/400/533',
    status: 'failed',
    isFavorited: false
  }
];

export const LANGUAGES = [
  { label: 'English', sub: 'English', value: 'en-US' },
  { label: '繁體中文', sub: 'Traditional Chinese', value: 'zh-TW' },
  { label: '日本語', sub: 'Japanese', value: 'ja-JP' },
  { label: '한국어', sub: 'Korean', value: 'ko-KR' },
  { label: 'Français', sub: 'French', value: 'fr-FR' },
  { label: 'Deutsch', sub: 'German', value: 'de-DE' },
  { label: 'Português', sub: 'Portuguese', value: 'pt-PT' },
  { label: 'Español', sub: 'Spanish', value: 'es-ES' },
  { label: 'Italiano', sub: 'Italian', value: 'it-IT' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'en-US': {
    nav_library: 'Library',
    nav_assets: 'Assets',
    nav_settings: 'Settings',
    header_upload: 'Upload',
    header_language: 'Language',
    header_profile: 'Profile',
    header_pro: 'Upgrade Pro',
    header_result: 'Avatar',
    btn_recharge: 'Top-up',
    btn_generate: 'Generate',
    btn_saving: 'Creating...',
    btn_save_album: 'Save',
    btn_regenerate: 'Retry',
    btn_delete: 'Delete',
    btn_save_changes: 'Save',
    btn_re_upload: 'Change',
    btn_continue_gen: 'More',
    label_coins: 'Balance',
    label_legal: 'Legal',
    label_privacy: 'Privacy',
    label_agreement: 'User Agreement',
    label_general: 'General',
    label_lang: 'Language',
    label_darkmode: 'Dark Mode',
    label_support: 'Support',
    label_contact: 'Contact Us',
    label_about: 'About Us',
    label_uploaded: 'Tap to Upload',
    label_upload_tip: 'Upload a clear front-facing photo for best results.',
    label_file_type: 'JPG, PNG (Max 5MB)',
    label_suggestions: 'Suggestions',
    label_suggestion_1: 'Clear',
    label_suggestion_2: 'Dark',
    label_suggestion_3: 'Blurry',
    label_cost: 'Cost',
    label_pro_title: 'Pro Avatars',
    label_pro_desc: 'Unlimited generation and HD downloads.',
    label_buy_now: 'Buy Now',
    label_restore: 'Restore',
    label_all: 'All',
    label_hot: 'Hot',
    label_completed: 'Done',
    label_processing: 'Processing',
    label_failed: 'Failed',
    label_empty: 'Empty',
    label_success: 'Success!',
    label_success_desc: 'Avatar generated, check your library.',
    label_view_assets: 'View Assets',
    label_category_fresh: 'Fresh',
    label_category_dreamy: 'Dreamy',
    label_category_cyber: 'Cyber',
    label_category_school: 'Daily',
    label_category_aesthetic: 'Pink',
    label_nickname: 'Nickname',
    label_official_email: 'Support Email',
    label_contact_desc: 'Feel free to contact our support team.',
    label_about_desc: 'Dynamic AI-Stylized Avatar uses advanced AI to create personalized digital personas.',
    label_version: 'Version',
    label_play: 'Play',
    label_queueing: 'In Queue...',
    label_fail_retry: 'Failed, coins refunded.',
    label_syncing: 'Syncing...',
    label_sync_tip: 'Downloading latest templates...'
  },
  'zh-TW': {
    nav_library: '模板庫',
    nav_assets: '我的素材',
    nav_settings: '設定',
    header_upload: '上傳照片',
    header_language: '選擇語言',
    header_profile: '個人資料',
    header_pro: '會員升級',
    header_result: '動態頭像',
    btn_recharge: '儲值',
    btn_generate: '開始生成',
    btn_saving: '正在創建...',
    btn_save_album: '保存',
    btn_regenerate: '重新生成',
    btn_delete: '刪除',
    btn_save_changes: '保存修改',
    btn_re_upload: '更換',
    btn_continue_gen: '繼續生成',
    label_coins: '餘額',
    label_legal: '法律與隱私',
    label_privacy: '隱私政策',
    label_agreement: '使用者協議',
    label_general: '通用',
    label_lang: '語言',
    label_darkmode: '深色模式',
    label_support: '支援',
    label_contact: '聯繫我們',
    label_about: '關於我們',
    label_uploaded: '點擊上傳',
    label_upload_tip: '請上傳一張光線充足、五官清晰的正面照片。',
    label_file_type: 'JPG, PNG (最大 5MB)',
    label_suggestions: '照片建議',
    label_suggestion_1: '正面清晰',
    label_suggestion_2: '光线昏暗',
    label_suggestion_3: '遮挡模糊',
    label_cost: '消耗',
    label_pro_title: '專業級動態頭像',
    label_pro_desc: '解鎖無限生成與高清下載特權。',
    label_buy_now: '立即購買',
    label_restore: '恢復購買',
    label_all: '全部',
    label_hot: '熱門',
    label_completed: '已完成',
    label_processing: '生成中',
    label_failed: '失敗',
    label_empty: '暫無內容',
    label_success: '成功！',
    label_success_desc: '您的頭像已進入製作隊列，請前往素材庫查看。',
    label_view_assets: '查看素材',
    label_category_fresh: '清新',
    label_category_dreamy: '夢幻',
    label_category_cyber: '賽博',
    label_category_school: '日常',
    label_category_aesthetic: '粉色',
    label_nickname: '暱稱',
    label_official_email: '官方郵箱',
    label_contact_desc: '如有任何問題，請隨時聯繫我們。',
    label_about_desc: 'Dynamic AI 致力於利用人工智慧為您打造極致的數位形象。',
    label_version: '版本',
    label_play: '點擊播放',
    label_queueing: '排隊中...',
    label_fail_retry: '生成失敗，金幣已退還。',
    label_syncing: '同步中...',
    label_sync_tip: '正在下載最新模板...'
  },
  'ja-JP': {
    nav_library: 'ライブラリ',
    nav_assets: 'アセット',
    nav_settings: '設定',
    header_upload: 'アップロード',
    header_language: '言語設定',
    header_profile: 'プロフィール',
    header_pro: 'プロ会員',
    header_result: 'アバター',
    btn_recharge: 'チャージ',
    btn_generate: '生成する',
    btn_saving: '作成中...',
    btn_save_album: '保存',
    btn_regenerate: '再試行',
    btn_delete: '削除',
    btn_save_changes: '保存する',
    btn_re_upload: '変更',
    btn_continue_gen: '続ける',
    label_coins: '残高',
    label_legal: '規約',
    label_privacy: 'プライバシー',
    label_agreement: '利用規約',
    label_general: '一般',
    label_lang: '言語',
    label_darkmode: 'ダークモード',
    label_support: 'サポート',
    label_contact: 'お問い合わせ',
    label_about: '私たちについて',
    label_uploaded: 'タップでアップ',
    label_upload_tip: '最高の結果を得るには、正面の鮮明な写真をアップしてください。',
    label_file_type: 'JPG, PNG (最大 5MB)',
    label_suggestions: '推奨事項',
    label_suggestion_1: '鮮明',
    label_suggestion_2: '暗い',
    label_suggestion_3: 'ぼやけ',
    label_cost: 'コスト',
    label_pro_title: 'プロアバター',
    label_pro_desc: '無制限の生成と高画質ダウンロード。',
    label_buy_now: '今すぐ購入',
    label_restore: '復元',
    label_all: 'すべて',
    label_hot: '人気',
    label_completed: '完了',
    label_processing: '生成中',
    label_failed: '失敗',
    label_empty: 'なし',
    label_success: '成功！',
    label_success_desc: 'アバターが生成されました。アセットを確認してください。',
    label_view_assets: 'アセットを表示',
    label_category_fresh: 'フレッシュ',
    label_category_dreamy: '夢心地',
    label_category_cyber: 'サイバー',
    label_category_school: '日常',
    label_category_aesthetic: 'ピンク',
    label_nickname: 'ニックネーム',
    label_official_email: 'メール',
    label_contact_desc: 'ご不明な点はお気軽にお問い合わせください。',
    label_about_desc: 'Dynamic AIは最先端のAIを使用して、究極のデジタルアバターを作成します。',
    label_version: 'バージョン',
    label_play: '再生',
    label_queueing: '待機中...',
    label_fail_retry: '失敗しました。コインは返却されました。',
    label_syncing: '同期中...',
    label_sync_tip: '最新テンプレートをダウンロード中...'
  },
  'ko-KR': {
    nav_library: '라이브러리',
    nav_assets: '에셋',
    nav_settings: '설정',
    header_upload: '업로드',
    header_language: '언어 설정',
    header_profile: '프로필',
    header_pro: '프로 업그레이드',
    header_result: '아바타',
    btn_recharge: '충전',
    btn_generate: '생성하기',
    btn_saving: '생성 중...',
    btn_save_album: '저장',
    btn_regenerate: '다시 시도',
    btn_delete: '삭제',
    btn_save_changes: '변경 저장',
    btn_re_upload: '변경',
    btn_continue_gen: '계속하기',
    label_coins: '잔액',
    label_legal: '법적 고지',
    label_privacy: '개인정보 처리방침',
    label_agreement: '이용약관',
    label_general: '일반',
    label_lang: '언어',
    label_darkmode: '다크 모드',
    label_support: '지원',
    label_contact: '문의하기',
    label_about: '소개',
    label_uploaded: '탭하여 업로드',
    label_upload_tip: '최상의 결과를 위해 정면의 선명한 사진을 업로드하세요.',
    label_file_type: 'JPG, PNG (최대 5MB)',
    label_suggestions: '추천 사항',
    label_suggestion_1: '선명함',
    label_suggestion_2: '어두움',
    label_suggestion_3: '흐림',
    label_cost: '비용',
    label_pro_title: '프로 아바타',
    label_pro_desc: '무제한 생성 및 HD 다운로드.',
    label_buy_now: '지금 구매',
    label_restore: '복구',
    label_all: '전체',
    label_hot: '인기',
    label_completed: '완료',
    label_processing: '생성 중',
    label_failed: '실패',
    label_empty: '비어 있음',
    label_success: '성공!',
    label_success_desc: '아바타가 생성되었습니다. 에셋을 확인하세요.',
    label_view_assets: '에셋 보기',
    label_category_fresh: '상쾌함',
    label_category_dreamy: '몽환적',
    label_category_cyber: '사이버',
    label_category_school: '일상',
    label_category_aesthetic: '핑크',
    label_nickname: '닉네임',
    label_official_email: '이메일',
    label_contact_desc: '문의 사항은 언제든지 연락주세요.',
    label_about_desc: 'Dynamic AI는 최신 AI 기술을 활용하여 개인화된 디지털 캐릭터를 만듭니다.',
    label_version: '버전',
    label_play: '재생',
    label_queueing: '대기 중...',
    label_fail_retry: '실패했습니다. 코인이 환불되었습니다.',
    label_syncing: '동기화 중...',
    label_sync_tip: '최신 템플릿 다운로드 중...'
  },
  'fr-FR': {
    nav_library: 'Bibliothèque',
    nav_assets: 'Galerie',
    nav_settings: 'Paramètres',
    header_upload: 'Télécharger',
    header_language: 'Langue',
    header_profile: 'Profil',
    header_pro: 'Version Pro',
    header_result: 'Avatar',
    btn_recharge: 'Recharger',
    btn_generate: 'Générer',
    btn_saving: 'Création...',
    btn_save_album: 'Enregistrer',
    btn_regenerate: 'Réessayer',
    btn_delete: 'Supprimer',
    btn_save_changes: 'Sauvegarder',
    btn_re_upload: 'Modifier',
    btn_continue_gen: 'Continuer',
    label_coins: 'Solde',
    label_legal: 'Légal',
    label_privacy: 'Confidentialité',
    label_agreement: 'Conditions',
    label_general: 'Général',
    label_lang: 'Langue',
    label_darkmode: 'Mode Sombre',
    label_support: 'Support',
    label_contact: 'Contact',
    label_about: 'À propos',
    label_uploaded: 'Cliquez pour uploader',
    label_upload_tip: 'Utilisez une photo nette de face pour un meilleur résultat.',
    label_file_type: 'JPG, PNG (Max 5Mo)',
    label_suggestions: 'Suggestions',
    label_suggestion_1: 'Net',
    label_suggestion_2: 'Sombre',
    label_suggestion_3: 'Flou',
    label_cost: 'Coût',
    label_pro_title: 'Avatars Pro',
    label_pro_desc: 'Générations illimitées et téléchargements HD.',
    label_buy_now: 'Acheter',
    label_restore: 'Restaurer',
    label_all: 'Tout',
    label_hot: 'Populaire',
    label_completed: 'Terminé',
    label_processing: 'Génération',
    label_failed: 'Échec',
    label_empty: 'Vide',
    label_success: 'Succès !',
    label_success_desc: 'Avatar généré, consultez votre galerie.',
    label_view_assets: 'Voir Galerie',
    label_category_fresh: 'Frais',
    label_category_dreamy: 'Rêveur',
    label_category_cyber: 'Cyber',
    label_category_school: 'Quotidien',
    label_category_aesthetic: 'Rose',
    label_nickname: 'Pseudo',
    label_official_email: 'E-mail Support',
    label_contact_desc: 'Contactez-nous pour toute question.',
    label_about_desc: 'Dynamic AI utilise l\'IA avancée pour créer des personas numériques uniques.',
    label_version: 'Version',
    label_play: 'Lire',
    label_queueing: 'En attente...',
    label_fail_retry: 'Échec, jetons remboursés.',
    label_syncing: 'Synchronisation...',
    label_sync_tip: 'Téléchargement des modèles...'
  },
  'de-DE': {
    nav_library: 'Bibliothek',
    nav_assets: 'Assets',
    nav_settings: 'Einstellungen',
    header_upload: 'Hochladen',
    header_language: 'Sprache',
    header_profile: 'Profil',
    header_pro: 'Pro Upgrade',
    header_result: 'Avatar',
    btn_recharge: 'Aufladen',
    btn_generate: 'Erstellen',
    btn_saving: 'Erstellt...',
    btn_save_album: 'Speichern',
    btn_regenerate: 'Wiederholen',
    btn_delete: 'Löschen',
    btn_save_changes: 'Speichern',
    btn_re_upload: 'Ändern',
    btn_continue_gen: 'Weiter',
    label_coins: 'Guthaben',
    label_legal: 'Rechtliches',
    label_privacy: 'Datenschutz',
    label_agreement: 'AGB',
    label_general: 'Allgemein',
    label_lang: 'Sprache',
    label_darkmode: 'Dunkelmodus',
    label_support: 'Support',
    label_contact: 'Kontakt',
    label_about: 'Über uns',
    label_uploaded: 'Zum Hochladen tippen',
    label_upload_tip: 'Laden Sie ein klares Frontalfoto für beste Ergebnisse hoch.',
    label_file_type: 'JPG, PNG (Max 5MB)',
    label_suggestions: 'Vorschläge',
    label_suggestion_1: 'Klar',
    label_suggestion_2: 'Dunkel',
    label_suggestion_3: 'Unscharf',
    label_cost: 'Kosten',
    label_pro_title: 'Pro Avatare',
    label_pro_desc: 'Unbegrenzte Generierung und HD-Downloads.',
    label_buy_now: 'Jetzt kaufen',
    label_restore: 'Wiederherstellen',
    label_all: 'Alle',
    label_hot: 'Beliebt',
    label_completed: 'Fertig',
    label_processing: 'Erstellt...',
    label_failed: 'Fehlgeschlagen',
    label_empty: 'Leer',
    label_success: 'Erfolg!',
    label_success_desc: 'Avatar erstellt, prüfen Sie Ihre Assets.',
    label_view_assets: 'Assets ansehen',
    label_category_fresh: 'Frisch',
    label_category_dreamy: 'Verträumt',
    label_category_cyber: 'Cyber',
    label_category_school: 'Alltag',
    label_category_aesthetic: 'Rosa',
    label_nickname: 'Spitzname',
    label_official_email: 'Support-E-Mail',
    label_contact_desc: 'Kontaktieren Sie unser Support-Team.',
    label_about_desc: 'Dynamic AI nutzt fortschrittliche KI für personalisierte Avatare.',
    label_version: 'Version',
    label_play: 'Abspielen',
    label_queueing: 'In Warteschlange...',
    label_fail_retry: 'Fehlgeschlagen, Münzen erstattet.',
    label_syncing: 'Synchronisiere...',
    label_sync_tip: 'Lade Vorlagen herunter...'
  },
  'pt-PT': {
    nav_library: 'Biblioteca',
    nav_assets: 'Galeria',
    nav_settings: 'Definições',
    header_upload: 'Carregar',
    header_language: 'Idioma',
    header_profile: 'Perfil',
    header_pro: 'Versão Pro',
    header_result: 'Avatar',
    btn_recharge: 'Recarregar',
    btn_generate: 'Gerar',
    btn_saving: 'A criar...',
    btn_save_album: 'Guardar',
    btn_regenerate: 'Repetir',
    btn_delete: 'Eliminar',
    btn_save_changes: 'Guardar',
    btn_re_upload: 'Mudar',
    btn_continue_gen: 'Continuar',
    label_coins: 'Saldo',
    label_legal: 'Legal',
    label_privacy: 'Privacidade',
    label_agreement: 'Termos',
    label_general: 'Geral',
    label_lang: 'Idioma',
    label_darkmode: 'Modo Escuro',
    label_support: 'Suporte',
    label_contact: 'Contacto',
    label_about: 'Sobre',
    label_uploaded: 'Toque para carregar',
    label_upload_tip: 'Carregue uma foto frontal nítida para melhores resultados.',
    label_file_type: 'JPG, PNG (Máx 5MB)',
    label_suggestions: 'Sugestões',
    label_suggestion_1: 'Nítido',
    label_suggestion_2: 'Escuro',
    label_suggestion_3: 'Borrão',
    label_cost: 'Custo',
    label_pro_title: 'Avatares Pro',
    label_pro_desc: 'Gerações ilimitadas e downloads em HD.',
    label_buy_now: 'Comprar Agora',
    label_restore: 'Restaurar',
    label_all: 'Tudo',
    label_hot: 'Popular',
    label_completed: 'Concluído',
    label_processing: 'A gerar',
    label_failed: 'Falhou',
    label_empty: 'Vazio',
    label_success: 'Sucesso!',
    label_success_desc: 'Avatar gerado, veja na sua galeria.',
    label_view_assets: 'Ver Galeria',
    label_category_fresh: 'Fresco',
    label_category_dreamy: 'Onírico',
    label_category_cyber: 'Cyber',
    label_category_school: 'Diário',
    label_category_aesthetic: 'Rosa',
    label_nickname: 'Apelido',
    label_official_email: 'Email Suporte',
    label_contact_desc: 'Contacte-nos para qualquer questão.',
    label_about_desc: 'Dynamic AI usa IA avançada para criar identidades digitais.',
    label_version: 'Versão',
    label_play: 'Reproduzir',
    label_queueing: 'Na fila...',
    label_fail_retry: 'Falhou, moedas reembolsadas.',
    label_syncing: 'A sincronizar...',
    label_sync_tip: 'A transferir modelos...'
  },
  'es-ES': {
    nav_library: 'Biblioteca',
    nav_assets: 'Mis Assets',
    nav_settings: 'Ajustes',
    header_upload: 'Subir',
    header_language: 'Idioma',
    header_profile: 'Perfil',
    header_pro: 'Upgrade Pro',
    header_result: 'Avatar',
    btn_recharge: 'Recargar',
    btn_generate: 'Generar',
    btn_saving: 'Creando...',
    btn_save_album: 'Guardar',
    btn_regenerate: 'Reintentar',
    btn_delete: 'Borrar',
    btn_save_changes: 'Guardar',
    btn_re_upload: 'Cambiar',
    btn_continue_gen: 'Seguir',
    label_coins: 'Saldo',
    label_legal: 'Legal',
    label_privacy: 'Privacidad',
    label_agreement: 'Términos',
    label_general: 'General',
    label_lang: 'Idioma',
    label_darkmode: 'Modo Oscuro',
    label_support: 'Soporte',
    label_contact: 'Contacto',
    label_about: 'Sobre nosotros',
    label_uploaded: 'Toca para subir',
    label_upload_tip: 'Sube una foto clara de frente para mejores resultados.',
    label_file_type: 'JPG, PNG (Máx 5MB)',
    label_suggestions: 'Sugerencias',
    label_suggestion_1: 'Claro',
    label_suggestion_2: 'Oscuro',
    label_suggestion_3: 'Borroso',
    label_cost: 'Coste',
    label_pro_title: 'Avatares Pro',
    label_pro_desc: 'Generación ilimitada y descargas HD.',
    label_buy_now: 'Comprar',
    label_restore: 'Restaurar',
    label_all: 'Todos',
    label_hot: 'Tendencia',
    label_completed: 'Listo',
    label_processing: 'Generando',
    label_failed: 'Error',
    label_empty: 'Vacío',
    label_success: '¡Éxito!',
    label_success_desc: 'Avatar generado, revisa tus assets.',
    label_view_assets: 'Ver Assets',
    label_category_fresh: 'Fresco',
    label_category_dreamy: 'Soñador',
    label_category_cyber: 'Cyber',
    label_category_school: 'Diario',
    label_category_aesthetic: 'Rosa',
    label_nickname: 'Apodo',
    label_official_email: 'Email Soporte',
    label_contact_desc: 'Contáctanos para cualquier duda.',
    label_about_desc: 'Dynamic AI usa IA avanzada para crear personajes digitales.',
    label_version: 'Versión',
    label_play: 'Reproducir',
    label_queueing: 'En cola...',
    label_fail_retry: 'Error, monedas devueltas.',
    label_syncing: 'Sincronizando...',
    label_sync_tip: 'Descargando plantillas...'
  },
  'it-IT': {
    nav_library: 'Libreria',
    nav_assets: 'Asset',
    nav_settings: 'Impostazioni',
    header_upload: 'Carica',
    header_language: 'Lingua',
    header_profile: 'Profilo',
    header_pro: 'Versione Pro',
    header_result: 'Avatar',
    btn_recharge: 'Ricarica',
    btn_generate: 'Genera',
    btn_saving: 'Creazione...',
    btn_save_album: 'Salva',
    btn_regenerate: 'Riprova',
    btn_delete: 'Elimina',
    btn_save_changes: 'Salva',
    btn_re_upload: 'Cambia',
    btn_continue_gen: 'Continua',
    label_coins: 'Saldo',
    label_legal: 'Legale',
    label_privacy: 'Privacy',
    label_agreement: 'Termini',
    label_general: 'Generale',
    label_lang: 'Lingua',
    label_darkmode: 'Modalità Scura',
    label_support: 'Supporto',
    label_contact: 'Contattaci',
    label_about: 'Su di noi',
    label_uploaded: 'Tocca per caricare',
    label_upload_tip: 'Carica una foto frontale nitida per risultati migliori.',
    label_file_type: 'JPG, PNG (Max 5MB)',
    label_suggestions: 'Suggerimenti',
    label_suggestion_1: 'Nitida',
    label_suggestion_2: 'Buia',
    label_suggestion_3: 'Sfocata',
    label_cost: 'Costo',
    label_pro_title: 'Avatar Pro',
    label_pro_desc: 'Generazione illimitata e download HD.',
    label_buy_now: 'Acquista',
    label_restore: 'Ripristina',
    label_all: 'Tutti',
    label_hot: 'Popolari',
    label_completed: 'Fatto',
    label_processing: 'In corso',
    label_failed: 'Fallito',
    label_empty: 'Vuoto',
    label_success: 'Successo!',
    label_success_desc: 'Avatar generato, controlla i tuoi asset.',
    label_view_assets: 'Vedi Asset',
    label_category_fresh: 'Fresco',
    label_category_dreamy: 'Onirico',
    label_category_cyber: 'Cyber',
    label_category_school: 'Diario',
    label_category_aesthetic: 'Rosa',
    label_nickname: 'Nickname',
    label_official_email: 'Email Supporto',
    label_contact_desc: 'Contattaci per qualsiasi domanda.',
    label_about_desc: 'Dynamic AI usa l\'IA avanzata per creare identità digitali.',
    label_version: 'Versione',
    label_play: 'Riproduci',
    label_queueing: 'In coda...',
    label_fail_retry: 'Errore, monete rimborsate.',
    label_syncing: 'Sincronizzazione...',
    label_sync_tip: 'Scaricamento modelli...'
  }
};
