
import { Template, Asset } from './types';

export const TEMPLATES: Template[] = [
  {
    id: '1',
    name: '樱花之梦',
    tag: '#粉色',
    imageUrl: 'https://picsum.photos/seed/cherry/400/533',
    isDynamic: true
  },
  {
    id: '2',
    name: '霓虹都市',
    tag: '#赛博朋克',
    imageUrl: 'https://picsum.photos/seed/neon/400/533',
    isDynamic: true
  },
  {
    id: '3',
    name: '夏日微风',
    tag: '#清新',
    imageUrl: 'https://picsum.photos/seed/summer/400/533',
    isDynamic: true
  },
  {
    id: '4',
    name: '惬意雨天',
    tag: '#治愈',
    imageUrl: 'https://picsum.photos/seed/rain/400/533',
    isDynamic: true
  },
  {
    id: '5',
    name: '校园时光',
    tag: '#日常',
    imageUrl: 'https://picsum.photos/seed/school/400/533',
    isDynamic: false
  },
  {
    id: '6',
    name: '星之魔法',
    tag: '#梦幻',
    imageUrl: 'https://picsum.photos/seed/magic/400/533',
    isDynamic: true
  }
];

export const MOCK_ASSETS: Asset[] = [
  {
    id: 'a1',
    name: '未来少女_V2',
    timestamp: '刚刚',
    imageUrl: 'https://picsum.photos/seed/cyber/400/533',
    status: 'completed',
    isDynamic: true,
    isFavorited: false
  },
  {
    id: 'a2',
    name: 'IMG_2931.jpg',
    timestamp: '2小时前',
    imageUrl: 'https://picsum.photos/seed/photo/400/533',
    status: 'original',
    isFavorited: true
  },
  {
    id: 'a3',
    name: '梦境_Final',
    timestamp: '生成中...',
    imageUrl: 'https://picsum.photos/seed/dream/400/533',
    status: 'processing',
    isFavorited: false
  },
  {
    id: 'a4',
    name: '赛博朋克_01',
    timestamp: '生成失败',
    imageUrl: 'https://picsum.photos/seed/cyber2/400/533',
    status: 'failed',
    isFavorited: false
  }
];

export const LANGUAGES = [
  { label: '简体中文', sub: 'Simplified Chinese', value: 'zh-CN' },
  { label: 'English', sub: 'English', value: 'en-US' },
  { label: '繁体中文', sub: 'Traditional Chinese', value: 'zh-TW' },
  { label: '日本語', sub: 'Japanese', value: 'ja-JP' },
  { label: '한국어', sub: 'Korean', value: 'ko-KR' },
  { label: 'Français', sub: 'French', value: 'fr-FR' },
  { label: 'Deutsch', sub: 'German', value: 'de-DE' },
  { label: 'Español', sub: 'Spanish', value: 'es-ES' }
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  'zh-CN': {
    nav_library: '模板库',
    nav_assets: '素材库',
    nav_settings: '设置',
    header_upload: '上传照片',
    header_language: '切换语言',
    header_profile: '个人资料',
    header_pro: '会员充值',
    header_result: '动态头像',
    btn_recharge: '充值',
    btn_generate: '开始生成',
    btn_saving: '正在创建...',
    btn_save_album: '保存相册',
    btn_regenerate: '重新生成',
    btn_delete: '删除',
    btn_save_changes: '保存修改',
    btn_re_upload: '更换',
    btn_continue_gen: '继续生成',
    label_coins: '我的金币',
    label_legal: '法律与协议',
    label_privacy: '隐私政策',
    label_agreement: '用户协议',
    label_general: '通用设置',
    label_lang: '语言',
    label_darkmode: '深色模式',
    label_support: '关于与支持',
    label_contact: '联系我们',
    label_about: '关于我们',
    label_uploaded: '点击上传照片',
    label_upload_tip: '为了获得最佳效果，请上传一张光线充足、五官清晰的正面照片。',
    label_file_type: '支持 JPG, PNG 格式 (最大 5MB)',
    label_suggestions: '照片建议',
    label_suggestion_1: '正面清晰',
    label_suggestion_2: '光线昏暗',
    label_suggestion_3: '遮挡面部',
    label_cost: '消耗',
    label_pro_title: '生成专属动漫头像',
    label_pro_desc: '购买金币包，尊享无限生成与高清下载特权',
    label_buy_now: '立即购买',
    label_restore: '恢复购买',
    label_all: '全部',
    label_hot: '热门',
    label_completed: '已生成',
    label_processing: '生成中',
    label_failed: '失败',
    label_empty: '暂无内容',
    label_success: '创建成功！',
    label_success_desc: '您的动态头像已经开始制作，可前往我的素材库查看',
    label_view_assets: '查看素材',
    label_category_fresh: '清新',
    label_category_dreamy: '梦幻',
    label_category_cyber: '赛博',
    label_category_school: '校园',
    label_category_aesthetic: '唯美',
    label_nickname: '昵称',
    label_official_email: '官方邮箱',
    label_contact_desc: '如有任何问题或建议，请随时联系一线支持团队。',
    label_about_desc: '灵动AI 致力于利用最尖端的生成式人工智能技术，为您打造极致的个性化数字分身体验。',
    label_version: '版本号',
    label_play: '点击播放',
    label_queueing: '正在排队生成中...',
    label_fail_retry: '生成失败，金币已经退回，请重试',
    label_syncing: '云端同步中',
    label_sync_tip: '正在从云端下载最新模板素材...'
  },
  'en-US': {
    nav_library: 'Library',
    nav_assets: 'Assets',
    nav_settings: 'Settings',
    header_upload: 'Upload',
    header_language: 'Language',
    header_profile: 'Profile',
    header_pro: 'Pro Upgrade',
    header_result: 'Avatar',
    btn_recharge: 'Top-up',
    btn_generate: 'Generate',
    btn_saving: 'Creating...',
    btn_save_album: 'Save',
    btn_regenerate: 'Retry',
    btn_delete: 'Delete',
    btn_save_changes: 'Save Changes',
    btn_re_upload: 'Change',
    btn_continue_gen: 'Keep Creating',
    label_coins: 'My Coins',
    label_legal: 'Legal',
    label_privacy: 'Privacy Policy',
    label_agreement: 'User Agreement',
    label_general: 'General',
    label_lang: 'Language',
    label_darkmode: 'Dark Mode',
    label_support: 'Support',
    label_contact: 'Contact Us',
    label_about: 'About Us',
    label_uploaded: 'Click to upload',
    label_upload_tip: 'Upload a clear front-facing photo for best results.',
    label_file_type: 'JPG, PNG (Max 5MB)',
    label_suggestions: 'Suggestions',
    label_suggestion_1: 'Clear Front',
    label_suggestion_2: 'Low Light',
    label_suggestion_3: 'Face Hidden',
    label_cost: 'Cost',
    label_pro_title: 'Pro Avatars',
    label_pro_desc: 'Buy coins for unlimited generation and HD downloads',
    label_buy_now: 'Buy Now',
    label_restore: 'Restore',
    label_all: 'All',
    label_hot: 'Hot',
    label_completed: 'Done',
    label_processing: 'Generating',
    label_failed: 'Failed',
    label_empty: 'Empty',
    label_success: 'Success!',
    label_success_desc: 'Your avatar is being made, check your library soon.',
    label_view_assets: 'View Assets',
    label_category_fresh: 'Fresh',
    label_category_dreamy: 'Dreamy',
    label_category_cyber: 'Cyber',
    label_category_school: 'School',
    label_category_aesthetic: 'Aesthetic',
    label_nickname: 'Nickname',
    label_official_email: 'Support Email',
    label_contact_desc: 'Contact us for any questions or feedback.',
    label_about_desc: 'Vivid AI is dedicated to using generative AI to create ultimate personalized digital avatars.',
    label_version: 'Version',
    label_play: 'Click to Play',
    label_queueing: 'In queue...',
    label_fail_retry: 'Failed, coins refunded, please retry',
    label_syncing: 'Syncing...',
    label_sync_tip: 'Downloading latest templates from cloud...'
  }
};
